### ISSUE TITLE
5.9.0: Transformer.filter_data_by_metadata() doesn't filter unselected nodes where selected unspecified

### ISSUE THREAD

**Issue by macleodmac** [singer-io/singer-python#120]
Hi,

I'm attempting to write a tap, using `singer.transform.Transformer.filter_data_by_metadata` in order to filter the data.

```python
    def filter_data_by_metadata(self, data, metadata):
        if isinstance(data, dict) and metadata:
            for field_name in list(data.keys()):
                selected = singer.metadata.get(metadata, ('properties', field_name), 'selected')
                inclusion = singer.metadata.get(metadata, ('properties', field_name), 'inclusion')
                if inclusion == 'automatic':
                    continue

                if selected is False:
                    data.pop(field_name, None)
                    # Track that a field was filtered because the customer
                    # didn't select it.
                    self.filtered.add(field_name)

                if inclusion == 'unsupported':
                    data.pop(field_name, None)
                    # Track that the field was filtered because the tap
                    # declared it as unsupported.
                    self.filtered.add(field_name)

        return data
```
This logic has two problems:
- If `selected` is missing in the metadata the field is not filtered
- `selected-by-default` is totally ignored

The expected behaviour would be the following:
- `selected` set to True, do nothing
- `selected` set to False, filter field
- `selected` missing and `selected-by-default` set to True, do nothing
- `selected` missing and `selected-by-default` set to True, filter field

**Comment by KAllan357** [comment]
There's a function in the utils module: https://github.com/singer-io/singer-python/blob/master/singer/utils.py#L237 `should_sync_field`. I think that the logic between this change and that function should be in agreement.
