### ISSUE TITLE
Problem in README example?

### ISSUE THREAD

**Issue by tjk** [singer-io/singer-python#9]
I don't remember how I got here and I'm really not a python person, but I think there might be an issue with your README example (that taught me something!)

In python 3 (which the README says your project depends on), I don't think `i` is in scope in the `write_state` line? (Turns out it leaks in python 2 -- http://stackoverflow.com/a/4199355/387413 -- and probably how this was tested?)

Cheers! (PS: cool project)

**Comment by karstendick** [comment]
Thanks for catching that, @tjk.

I've updated the README in https://github.com/singer-io/singer-python/commit/d07e00ce28e44ffc1606c2f210d3ea42a8181007
